### Ping Api
GET  {{host}}/api/ping

### 测试 ID 插入
POST {{host}}/api/id/validate 
content-type: application/json

{
    "address": "0x9A9737e821bb216EF74Cd0E6b2Dd3E4FfF98C681",
    "baseAddress": "0x9A9737e821bb216EF74Cd0E6b2Dd3E4FfF98C681",
    "lensHandle": "",
    "platform": 1
}

### 测试 ID 插入
GET {{host}}/api/id/list?address={{cl_addr}}

### 测试 SBT 技能
GET {{host}}/api/id/sbt?address={{cl_addr}}

### 测试 SBT 详情
GET {{host}}/api/sbt?address={{sbt_addr}}&tokenId={{sbt_id}}

### 测试 推荐
GET {{host}}/api/id/recommendation?address={{cl_addr}}

### 获得 Q11e
GET {{host}}/api/q11e?address={{cl_addr}}

### 开发测试发放 Ensoul SBT
POST {{host}}/api/test/sbt
content-type: application/json

{
    "toAddr": "0x27aa5a880B512bEaF40D1B2E0F256b09f5711444",
    "tokenId": "0"
}

### 测试增加 Follow
POST {{host}}/api/follow
content-type: application/json

{
    "toAddr": "{{cl2_addr}}",
    "fromAddr": "{{cl_addr}}"
}

### 测试查询 Follow
GET {{host}}/api/follow?toAddr={{cl2_addr}}&fromAddr={{cl_addr}}

### 测试查询所有 Following 
GET {{host}}/api/follow/following?addr={{cl_addr}}&vistorAddress={{cl3_addr}}

### 测试查询所有 Follower
GET {{host}}/api/follow/follower?addr={{cl2_addr}}&vistorAddress={{cl3_addr}}

### 查新用户
GET {{host}}/api/id/new

### 聪哥 Debug
GET {{host}}/api/follow/following?addr=0x27aa5a880B512bEaF40D1B2E0F256b09f5711444

