[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[dev]
  targetPort = 3000

[[edge_functions]]
  path = "/org/*"
  function = "botmeta"

[[edge_functions]]
  path = "/series/seriesintro/*"
  function = "botmeta"

[[edge_functions]]
  path = "/courses/course/*"
  function = "botmeta"

[[redirects]]
  from = "/apiDevelopment/*"
  to = "http://dev.node-api.deschool.app:8001/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/apiStaging/*"
  to = "http://stg.node-api.deschool.app:8000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/apiProduction/*"
  to = "http://node-api.deschool.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/goapiDevelopment/*"
  to = "http://dev.api.deschool.app:8001/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/goapiStaging/*"
  to = "http://stg.api.deschool.app:8000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/goapiProduction/*"
  to = "http://api.deschool.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/goapiBoothStg/*"
  to = "http://54.90.108.215/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/goapiBoothPrd/*"
  to = "http://ec2-54-211-102-5.compute-1.amazonaws.com:80/api/:splat"
  status = 200
  force = true


  [[redirects]]
  from = "/ccProfile/*"
  to = "https://api.cyberconnect.dev/profile/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/mypinata/*"
  to = "https://deschool.mypinata.cloud/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/awsResource/*"
  to = "https://deschool.s3.amazonaws.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


